# Author: William Lam
# Website: www.virtuallyghetto
# Product: VMware vCloud Director 5.1
# Description: YAML input for vCloud Director
# Reference: http://www.williamlam.com/2013/02/exploring-vcloud-api-using-ruby.html
:username: administrator@system
:password: supersecretpassword
:site: https://vcd.primp-industries.com
